# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@adobe/css-tools-4.3.3" = {
      name = "_at_adobe_slash_css-tools";
      packageName = "@adobe/css-tools";
      version = "4.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@adobe/css-tools/-/css-tools-4.3.3.tgz";
        sha512 = "rE0Pygv0sEZ4vBWHlAgJLGDU7Pm8xoO6p3wsEceb7GYAjScrOHpEo8KK/eVkAcnSM+slAEtXjA2JpdjLp4fJQQ==";
      };
    };
    "@bufbuild/protobuf-2.2.5" = {
      name = "_at_bufbuild_slash_protobuf";
      packageName = "@bufbuild/protobuf";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@bufbuild/protobuf/-/protobuf-2.2.5.tgz";
        sha512 = "/g5EzJifw5GF8aren8wZ/G5oMuPoGeS6MQD3ca8ddcvdXR5UELUfdTZITCGNhNXynY/AYl3Z4plmxdj/tRl/hQ==";
      };
    };
    "@esbuild/linux-x64-0.21.5" = {
      name = "_at_esbuild_slash_linux-x64";
      packageName = "@esbuild/linux-x64";
      version = "0.21.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.21.5.tgz";
        sha512 = "1rYdTpyv03iycF1+BhzrzQJCdOuAOtaqHTWJZCWvijKD2N5Xu0TtVC8/+1faWqcP9iBCWOmjmhoH94dH82BxPQ==";
      };
    };
    "@isaacs/cliui-8.0.2" = {
      name = "_at_isaacs_slash_cliui";
      packageName = "@isaacs/cliui";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@isaacs/cliui/-/cliui-8.0.2.tgz";
        sha512 = "O8jcjabXaleOG9DQ0+ARXWZBTfnP4WNAqzuiJK7ll44AmxGKv/J2M4TPjxjY3znBCfvBXFzucm1twdyFybFqEA==";
      };
    };
    "@jridgewell/gen-mapping-0.3.8" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.8.tgz";
        sha512 = "imAbBGkb+ebQyxKgzv5Hu2nmROxoDOXHh80evxdoXNOrvAnVx7zimzc1Oo5h9RlfV4vPXaE2iM5pOFbvOCClWA==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/set-array-1.2.1" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.2.1.tgz";
        sha512 = "R8gLRTZeyp03ymzP/6Lil/28tGeGEzhx1q2k703KGWRAI1VdvPIXdG70VJc2pAMw3NA6JKL5hhFu1sJX0Mnn/A==";
      };
    };
    "@jridgewell/source-map-0.3.6" = {
      name = "_at_jridgewell_slash_source-map";
      packageName = "@jridgewell/source-map";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/source-map/-/source-map-0.3.6.tgz";
        sha512 = "1ZJTZebgqllO79ue2bm3rIGud/bOe0pP5BjSRCRxxYkEZS8STV7zN84UBbiYu7jy+eCKSnVIUgoWWE/tt+shMQ==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.0" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.0.tgz";
        sha512 = "gv3ZRaISU3fjPAgNsriBRqGWQL6quFx04YMPW/zD8XMLsU32mhCCbfbO6KZFLjvYpCZ8zyDEgqsgf+PwPaM7GQ==";
      };
    };
    "@jridgewell/trace-mapping-0.3.25" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.25.tgz";
        sha512 = "vNk6aEwybGtawWmy/PzwnGDOjCkLWSD2wqvjGGAgOAwCGWySYXfYoxt00IJkTF+8Lb57DwOb3Aa0o9CApepiYQ==";
      };
    };
    "@remirror/core-constants-3.0.0" = {
      name = "_at_remirror_slash_core-constants";
      packageName = "@remirror/core-constants";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@remirror/core-constants/-/core-constants-3.0.0.tgz";
        sha512 = "42aWfPrimMfDKDi4YegyS7x+/0tlzaqwPQCULLanv3DMIlu96KTJR0fM5isWX2UViOqlGnX6YFgqWepcX+XMNg==";
      };
    };
    "@rollup/rollup-linux-x64-gnu-4.36.0" = {
      name = "_at_rollup_slash_rollup-linux-x64-gnu";
      packageName = "@rollup/rollup-linux-x64-gnu";
      version = "4.36.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/rollup-linux-x64-gnu/-/rollup-linux-x64-gnu-4.36.0.tgz";
        sha512 = "5KtoW8UWmwFKQ96aQL3LlRXX16IMwyzMq/jSSVIIyAANiE1doaQsx/KRyhAvpHlPjPiSU/AYX/8m+lQ9VToxFQ==";
      };
    };
    "@tailwindcss/forms-0.5.10" = {
      name = "_at_tailwindcss_slash_forms";
      packageName = "@tailwindcss/forms";
      version = "0.5.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/forms/-/forms-0.5.10.tgz";
        sha512 = "utI1ONF6uf/pPNO68kmN1b8rEwNXv3czukalo8VtJH8ksIkZXr3Q3VYudZLkCsDd4Wku120uF02hYK25XGPorw==";
      };
    };
    "@tailwindcss/node-4.0.15" = {
      name = "_at_tailwindcss_slash_node";
      packageName = "@tailwindcss/node";
      version = "4.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/node/-/node-4.0.15.tgz";
        sha512 = "IODaJjNmiasfZX3IoS+4Em3iu0fD2HS0/tgrnkYfW4hyUor01Smnr5eY3jc4rRgaTDrJlDmBTHbFO0ETTDaxWA==";
      };
    };
    "@tailwindcss/oxide-4.0.15" = {
      name = "_at_tailwindcss_slash_oxide";
      packageName = "@tailwindcss/oxide";
      version = "4.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide/-/oxide-4.0.15.tgz";
        sha512 = "e0uHrKfPu7JJGMfjwVNyt5M0u+OP8kUmhACwIRlM+JNBuReDVQ63yAD1NWe5DwJtdaHjugNBil76j+ks3zlk6g==";
      };
    };
    "@tailwindcss/oxide-linux-x64-gnu-4.0.15" = {
      name = "_at_tailwindcss_slash_oxide-linux-x64-gnu";
      packageName = "@tailwindcss/oxide-linux-x64-gnu";
      version = "4.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-linux-x64-gnu/-/oxide-linux-x64-gnu-4.0.15.tgz";
        sha512 = "g76GxlKH124RuGqacCEFc2nbzRl7bBrlC8qDQMiUABkiifDRHOIUjgKbLNG4RuR9hQAD/MKsqZ7A8L08zsoBrw==";
      };
    };
    "@tailwindcss/typography-0.5.16" = {
      name = "_at_tailwindcss_slash_typography";
      packageName = "@tailwindcss/typography";
      version = "0.5.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/typography/-/typography-0.5.16.tgz";
        sha512 = "0wDLwCVF5V3x3b1SGXPCDcdsbDHMBe+lkFzBRaHeLvNi+nrrnZ1lA18u+OTWO8iSWU2GxUOCvlXtDuqftc1oiA==";
      };
    };
    "@tailwindcss/vite-4.0.15" = {
      name = "_at_tailwindcss_slash_vite";
      packageName = "@tailwindcss/vite";
      version = "4.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/vite/-/vite-4.0.15.tgz";
        sha512 = "JRexava80NijI8cTcLXNM3nQL5A0ptTHI8oJLLe8z1MpNB6p5J4WCdJJP8RoyHu8/eB1JzEdbpH86eGfbuaezQ==";
      };
    };
    "@tiptap/core-2.11.5" = {
      name = "_at_tiptap_slash_core";
      packageName = "@tiptap/core";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/core/-/core-2.11.5.tgz";
        sha512 = "jb0KTdUJaJY53JaN7ooY3XAxHQNoMYti/H6ANo707PsLXVeEqJ9o8+eBup1JU5CuwzrgnDc2dECt2WIGX9f8Jw==";
      };
    };
    "@tiptap/extension-blockquote-2.11.5" = {
      name = "_at_tiptap_slash_extension-blockquote";
      packageName = "@tiptap/extension-blockquote";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-blockquote/-/extension-blockquote-2.11.5.tgz";
        sha512 = "MZfcRIzKRD8/J1hkt/eYv49060GTL6qGR3NY/oTDuw2wYzbQXXLEbjk8hxAtjwNn7G+pWQv3L+PKFzZDxibLuA==";
      };
    };
    "@tiptap/extension-bold-2.11.5" = {
      name = "_at_tiptap_slash_extension-bold";
      packageName = "@tiptap/extension-bold";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-bold/-/extension-bold-2.11.5.tgz";
        sha512 = "OAq03MHEbl7MtYCUzGuwb0VpOPnM0k5ekMbEaRILFU5ZC7cEAQ36XmPIw1dQayrcuE8GZL35BKub2qtRxyC9iA==";
      };
    };
    "@tiptap/extension-bullet-list-2.11.5" = {
      name = "_at_tiptap_slash_extension-bullet-list";
      packageName = "@tiptap/extension-bullet-list";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-bullet-list/-/extension-bullet-list-2.11.5.tgz";
        sha512 = "VXwHlX6A/T6FAspnyjbKDO0TQ+oetXuat6RY1/JxbXphH42nLuBaGWJ6pgy6xMl6XY8/9oPkTNrfJw/8/eeRwA==";
      };
    };
    "@tiptap/extension-code-2.11.5" = {
      name = "_at_tiptap_slash_extension-code";
      packageName = "@tiptap/extension-code";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-code/-/extension-code-2.11.5.tgz";
        sha512 = "xOvHevNIQIcCCVn9tpvXa1wBp0wHN/2umbAZGTVzS+AQtM7BTo0tz8IyzwxkcZJaImONcUVYLOLzt2AgW1LltA==";
      };
    };
    "@tiptap/extension-code-block-2.11.5" = {
      name = "_at_tiptap_slash_extension-code-block";
      packageName = "@tiptap/extension-code-block";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-code-block/-/extension-code-block-2.11.5.tgz";
        sha512 = "ksxMMvqLDlC+ftcQLynqZMdlJT1iHYZorXsXw/n+wuRd7YElkRkd6YWUX/Pq/njFY6lDjKiqFLEXBJB8nrzzBA==";
      };
    };
    "@tiptap/extension-document-2.11.5" = {
      name = "_at_tiptap_slash_extension-document";
      packageName = "@tiptap/extension-document";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-document/-/extension-document-2.11.5.tgz";
        sha512 = "7I4BRTpIux2a0O2qS3BDmyZ5LGp3pszKbix32CmeVh7lN9dV7W5reDqtJJ9FCZEEF+pZ6e1/DQA362dflwZw2g==";
      };
    };
    "@tiptap/extension-dropcursor-2.11.5" = {
      name = "_at_tiptap_slash_extension-dropcursor";
      packageName = "@tiptap/extension-dropcursor";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-dropcursor/-/extension-dropcursor-2.11.5.tgz";
        sha512 = "uIN7L3FU0904ec7FFFbndO7RQE/yiON4VzAMhNn587LFMyWO8US139HXIL4O8dpZeYwYL3d1FnDTflZl6CwLlg==";
      };
    };
    "@tiptap/extension-gapcursor-2.11.5" = {
      name = "_at_tiptap_slash_extension-gapcursor";
      packageName = "@tiptap/extension-gapcursor";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-gapcursor/-/extension-gapcursor-2.11.5.tgz";
        sha512 = "kcWa+Xq9cb6lBdiICvLReuDtz/rLjFKHWpW3jTTF3FiP3wx4H8Rs6bzVtty7uOVTfwupxZRiKICAMEU6iT0xrQ==";
      };
    };
    "@tiptap/extension-hard-break-2.11.5" = {
      name = "_at_tiptap_slash_extension-hard-break";
      packageName = "@tiptap/extension-hard-break";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-hard-break/-/extension-hard-break-2.11.5.tgz";
        sha512 = "q9doeN+Yg9F5QNTG8pZGYfNye3tmntOwch683v0CCVCI4ldKaLZ0jG3NbBTq+mosHYdgOH2rNbIORlRRsQ+iYQ==";
      };
    };
    "@tiptap/extension-heading-2.11.5" = {
      name = "_at_tiptap_slash_extension-heading";
      packageName = "@tiptap/extension-heading";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-heading/-/extension-heading-2.11.5.tgz";
        sha512 = "x/MV53psJ9baRcZ4k4WjnCUBMt8zCX7mPlKVT+9C/o+DEs/j/qxPLs95nHeQv70chZpSwCQCt93xMmuF0kPoAg==";
      };
    };
    "@tiptap/extension-history-2.11.5" = {
      name = "_at_tiptap_slash_extension-history";
      packageName = "@tiptap/extension-history";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-history/-/extension-history-2.11.5.tgz";
        sha512 = "b+wOS33Dz1azw6F1i9LFTEIJ/gUui0Jwz5ZvmVDpL2ZHBhq1Ui0/spTT+tuZOXq7Y/uCbKL8Liu4WoedIvhboQ==";
      };
    };
    "@tiptap/extension-horizontal-rule-2.11.5" = {
      name = "_at_tiptap_slash_extension-horizontal-rule";
      packageName = "@tiptap/extension-horizontal-rule";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-horizontal-rule/-/extension-horizontal-rule-2.11.5.tgz";
        sha512 = "3up2r1Du8/5/4ZYzTC0DjTwhgPI3dn8jhOCLu73m5F3OGvK/9whcXoeWoX103hYMnGDxBlfOje71yQuN35FL4A==";
      };
    };
    "@tiptap/extension-italic-2.11.5" = {
      name = "_at_tiptap_slash_extension-italic";
      packageName = "@tiptap/extension-italic";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-italic/-/extension-italic-2.11.5.tgz";
        sha512 = "9VGfb2/LfPhQ6TjzDwuYLRvw0A6VGbaIp3F+5Mql8XVdTBHb2+rhELbyhNGiGVR78CaB/EiKb6dO9xu/tBWSYA==";
      };
    };
    "@tiptap/extension-link-2.11.5" = {
      name = "_at_tiptap_slash_extension-link";
      packageName = "@tiptap/extension-link";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-link/-/extension-link-2.11.5.tgz";
        sha512 = "4Iu/aPzevbYpe50xDI0ZkqRa6nkZ9eF270Ue2qaF3Ab47nehj+9Jl78XXzo8+LTyFMnrETI73TAs1aC/IGySeQ==";
      };
    };
    "@tiptap/extension-list-item-2.11.5" = {
      name = "_at_tiptap_slash_extension-list-item";
      packageName = "@tiptap/extension-list-item";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-list-item/-/extension-list-item-2.11.5.tgz";
        sha512 = "Mp5RD/pbkfW1vdc6xMVxXYcta73FOwLmblQlFNn/l/E5/X1DUSA4iGhgDDH4EWO3swbs03x2f7Zka/Xoj3+WLg==";
      };
    };
    "@tiptap/extension-ordered-list-2.11.5" = {
      name = "_at_tiptap_slash_extension-ordered-list";
      packageName = "@tiptap/extension-ordered-list";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-ordered-list/-/extension-ordered-list-2.11.5.tgz";
        sha512 = "Cu8KwruBNWAaEfshRQR0yOSaUKAeEwxW7UgbvF9cN/zZuKgK5uZosPCPTehIFCcRe+TBpRtZQh+06f/gNYpYYg==";
      };
    };
    "@tiptap/extension-paragraph-2.11.5" = {
      name = "_at_tiptap_slash_extension-paragraph";
      packageName = "@tiptap/extension-paragraph";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-paragraph/-/extension-paragraph-2.11.5.tgz";
        sha512 = "YFBWeg7xu/sBnsDIF/+nh9Arf7R0h07VZMd0id5Ydd2Qe3c1uIZwXxeINVtH0SZozuPIQFAT8ICe9M0RxmE+TA==";
      };
    };
    "@tiptap/extension-strike-2.11.5" = {
      name = "_at_tiptap_slash_extension-strike";
      packageName = "@tiptap/extension-strike";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-strike/-/extension-strike-2.11.5.tgz";
        sha512 = "PVfUiCqrjvsLpbIoVlegSY8RlkR64F1Rr2RYmiybQfGbg+AkSZXDeO0eIrc03//4gua7D9DfIozHmAKv1KN3ow==";
      };
    };
    "@tiptap/extension-text-2.11.5" = {
      name = "_at_tiptap_slash_extension-text";
      packageName = "@tiptap/extension-text";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-text/-/extension-text-2.11.5.tgz";
        sha512 = "Gq1WwyhFpCbEDrLPIHt5A8aLSlf8bfz4jm417c8F/JyU0J5dtYdmx0RAxjnLw1i7ZHE7LRyqqAoS0sl7JHDNSQ==";
      };
    };
    "@tiptap/extension-text-style-2.11.5" = {
      name = "_at_tiptap_slash_extension-text-style";
      packageName = "@tiptap/extension-text-style";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/extension-text-style/-/extension-text-style-2.11.5.tgz";
        sha512 = "YUmYl0gILSd/u/ZkOmNxjNXVw+mu8fpC2f8G4I4tLODm0zCx09j9DDEJXSrM5XX72nxJQqtSQsCpNKnL0hfeEQ==";
      };
    };
    "@tiptap/html-2.11.5" = {
      name = "_at_tiptap_slash_html";
      packageName = "@tiptap/html";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/html/-/html-2.11.5.tgz";
        sha512 = "B7ZuFV4Z6JytBhcj4865yGldPite+xX7O3X4hBUNoPpxhDf7BD+lSOgeZabZteQPnP6TKKqFT50q/Wll2t8eGQ==";
      };
    };
    "@tiptap/pm-2.11.5" = {
      name = "_at_tiptap_slash_pm";
      packageName = "@tiptap/pm";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/pm/-/pm-2.11.5.tgz";
        sha512 = "z9JFtqc5ZOsdQLd9vRnXfTCQ8v5ADAfRt9Nm7SqP6FUHII8E1hs38ACzf5xursmth/VonJYb5+73Pqxk1hGIPw==";
      };
    };
    "@tiptap/starter-kit-2.11.5" = {
      name = "_at_tiptap_slash_starter-kit";
      packageName = "@tiptap/starter-kit";
      version = "2.11.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tiptap/starter-kit/-/starter-kit-2.11.5.tgz";
        sha512 = "SLI7Aj2ruU1t//6Mk8f+fqW+18uTqpdfLUJYgwu0CkqBckrkRZYZh6GVLk/02k3H2ki7QkFxiFbZrdbZdng0JA==";
      };
    };
    "@types/estree-1.0.6" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.6.tgz";
        sha512 = "AYnb1nQyY49te+VRAVgmzfcgjYS91mY5P0TKUDCLEM+gNnA+3T6rWITXRLYCpahpqSQbN5cE+gHpnPyXjHWxcw==";
      };
    };
    "@types/linkify-it-5.0.0" = {
      name = "_at_types_slash_linkify-it";
      packageName = "@types/linkify-it";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/linkify-it/-/linkify-it-5.0.0.tgz";
        sha512 = "sVDA58zAw4eWAffKOaQH5/5j3XeayukzDk+ewSsnv3p4yJEZHCCzMDiZM8e0OUrRvmpGZ85jf4yDHkHsgBNr9Q==";
      };
    };
    "@types/markdown-it-14.1.2" = {
      name = "_at_types_slash_markdown-it";
      packageName = "@types/markdown-it";
      version = "14.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/markdown-it/-/markdown-it-14.1.2.tgz";
        sha512 = "promo4eFwuiW+TfGxhi+0x3czqTYJkG8qB17ZUJiVF10Xm7NLVRSLUsfRTU/6h1e24VvRnXCx+hG7li58lkzog==";
      };
    };
    "@types/mdurl-2.0.0" = {
      name = "_at_types_slash_mdurl";
      packageName = "@types/mdurl";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mdurl/-/mdurl-2.0.0.tgz";
        sha512 = "RGdgjQUZba5p6QEFAVx2OGb8rQDL/cPRG7GiedRzMcJ1tYnUANBncjbSB1NRGwbvjcPeikRABz2nshyPk1bhWg==";
      };
    };
    "@types/node-22.13.11" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "22.13.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-22.13.11.tgz";
        sha512 = "iEUCUJoU0i3VnrCmgoWCXttklWcvoCIx4jzcP22fioIVSdTmjgoEvmAO/QPw6TcS9k5FrNgn4w7q5lGOd1CT5g==";
      };
    };
    "acorn-8.14.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.14.1.tgz";
        sha512 = "OvQ/2pUDKmgfCg++xsTX1wGxfTaszcHVcTctW4UJB4hibJx2HXxxO5UmVgyjMa+ZDsiaf5wWLXYpRWMmBI0QHg==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-regex-6.1.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.1.0.tgz";
        sha512 = "7HSX4QQb4CspciLpVFwyRe79O3xsIZDDLER21kERQ71oaPodF8jL725AgJMFAYbooIqolJoRLuM81SpeUkpkvA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "ansi-styles-6.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.1.tgz";
        sha512 = "bN798gFfQX+viw3R7yrGWRqnrN2oRkEkUjjl4JNn4E8GxxbjtG3FbrEIIY3l8/hrwUwIeCZvi4QuOTP4MErVug==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "buffer-builder-0.2.0" = {
      name = "buffer-builder";
      packageName = "buffer-builder";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-builder/-/buffer-builder-0.2.0.tgz";
        sha512 = "7VPMEPuYznPSoR21NE1zvd2Xna6c/CloiZCfcMXR1Jny6PjX0N4Nsa38zcBFo/FMK+BlA+FLKbJCQ0i2yxp+Xg==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "chokidar-4.0.3" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-4.0.3.tgz";
        sha512 = "Qgzu8kfBvo+cA4962jnP1KkS6Dop5NS6g7R5LFYJr4b8Ub94PPQXUksCw9PvXoeXPRRddRNC5C1JQUR2SMGtnA==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "colorjs.io-0.5.2" = {
      name = "colorjs.io";
      packageName = "colorjs.io";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorjs.io/-/colorjs.io-0.5.2.tgz";
        sha512 = "twmVoizEW7ylZSN32OgKdXRmo1qg+wT5/6C3xu5b9QsWzSFAhHLn2xd8ro0diCsKfCj1RdaTP/nrcW+vAoQPIw==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "copy-anything-2.0.6" = {
      name = "copy-anything";
      packageName = "copy-anything";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-anything/-/copy-anything-2.0.6.tgz";
        sha512 = "1j20GZTsvKNkc4BY3NpMOM8tt///wY3FpIzozTOFO2ffuZcV61nojHXVKIy3WM+7ADCy5FVhdZYHYDdgTU0yJw==";
      };
    };
    "crelt-1.0.6" = {
      name = "crelt";
      packageName = "crelt";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/crelt/-/crelt-1.0.6.tgz";
        sha512 = "VQ2MBenTq1fWZUH9DJNGti7kKv6EeAuYr3cLwxUWhIu1baTaXh4Ib5W2CqHVqib4/MqbYGJqiL3Zb8GJZr3l4g==";
      };
    };
    "cross-spawn-7.0.6" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
        sha512 = "uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
      };
    };
    "css-what-6.1.0" = {
      name = "css-what";
      packageName = "css-what";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-6.1.0.tgz";
        sha512 = "HTUrgRJ7r4dsZKU6GjmpfRK1O76h97Z8MfS1G0FozR+oF2kG6Vfe8JE6zwrkbxigziPHinCJ+gCPjA9EaBDtRw==";
      };
    };
    "cssesc-3.0.0" = {
      name = "cssesc";
      packageName = "cssesc";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz";
        sha512 = "/Tb/JcjK111nNScGob5MNtsntNM1aCNUDipB/TkwZFhyDrrE47SOx/18wF2bbjgc3ZzCSKW1T5nt5EbFoAz/Vg==";
      };
    };
    "debug-4.4.0" = {
      name = "debug";
      packageName = "debug";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.4.0.tgz";
        sha512 = "6WTZ/IxCY/T6BALoZHaE4ctp9xm+Z5kY/pzYaCHRFeyVhojxlrm+46y68HA6hr0TcwEssoxNiDEUJQjfPZ/RYA==";
      };
    };
    "detect-libc-2.0.3" = {
      name = "detect-libc";
      packageName = "detect-libc";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.3.tgz";
        sha512 = "bwy0MGW55bG41VqxxypOsdSdGqLwXPI/focwgTYCFMbdUiBAxLg9CFzG08sz2aqzknwiX7Hkl0bQENjg8iLByw==";
      };
    };
    "eastasianwidth-0.2.0" = {
      name = "eastasianwidth";
      packageName = "eastasianwidth";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eastasianwidth/-/eastasianwidth-0.2.0.tgz";
        sha512 = "I88TYZWc9XiYHRQ4/3c5rjjfgkjhLyW2luGIheGERbNQ6OY7yTybanSpDXZa8y7VUP9YmDcYa+eyq4ca7iLqWA==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "emoji-regex-9.2.2" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "9.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-9.2.2.tgz";
        sha512 = "L18DaJsXSUk2+42pv8mLs5jJT2hqFkFE4j21wOmgbUqsZ2hL72NsUU785g9RXgo3s0ZNgVl42TiHp3ZtOv/Vyg==";
      };
    };
    "enhanced-resolve-5.18.1" = {
      name = "enhanced-resolve";
      packageName = "enhanced-resolve";
      version = "5.18.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/enhanced-resolve/-/enhanced-resolve-5.18.1.tgz";
        sha512 = "ZSW3ma5GkcQBIpwZTSRAI8N71Uuwgs93IezB7mf7R60tC8ZbJideoDNKjHn2O9KIlx6rkGTTEk1xUCK2E1Y2Yg==";
      };
    };
    "entities-4.5.0" = {
      name = "entities";
      packageName = "entities";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-4.5.0.tgz";
        sha512 = "V0hjH4dGPh9Ao5p0MoRY6BVqtwCjhz6vI5LT8AJ55H+4g9/4vbHx1I54fS0XuclLhDHArPQCiMjDxjaL8fPxhw==";
      };
    };
    "entities-5.0.0" = {
      name = "entities";
      packageName = "entities";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-5.0.0.tgz";
        sha512 = "BeJFvFRJddxobhvEdm5GqHzRV/X+ACeuw0/BuuxsCh1EUZcAIz8+kYmBp/LrQuloy6K1f3a0M7+IhmZ7QnkISA==";
      };
    };
    "errno-0.1.8" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.8.tgz";
        sha512 = "dJ6oBr5SQ1VSd9qkk7ByRgb/1SH4JZjCHSW/mr63/QcXO9zLVxvJ6Oy13nio03rxpSnVDDjFor75SjVeZWPW/A==";
      };
    };
    "esbuild-0.21.5" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.21.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.21.5.tgz";
        sha512 = "mg3OPMV4hXywwpoDxu3Qda5xCKQi+vCTZq8S9J/EpkhB2HzKXq4SNFZE3+NK93JYxc8VMSep+lOUSC/RVKaBqw==";
      };
    };
    "escape-string-regexp-4.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-4.0.0.tgz";
        sha512 = "TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==";
      };
    };
    "foreground-child-3.3.1" = {
      name = "foreground-child";
      packageName = "foreground-child";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreground-child/-/foreground-child-3.3.1.tgz";
        sha512 = "gIXjKqtFuWEgzFRJA9WCQeSJLZDjgJUOMCMzxtvFq/37KojM1BFGufqsCy0r4qSQmYLsZYMeyRqzIWOMup03sw==";
      };
    };
    "glob-10.4.5" = {
      name = "glob";
      packageName = "glob";
      version = "10.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-10.4.5.tgz";
        sha512 = "7Bv8RF0k6xjo7d4A/PxYLbUCfb6c+Vpd2/mB2yRDlew7Jb5hEXiCD9ibfO7wpk8i4sevK6DFny9h7EYbM3/sHg==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "image-size-0.5.5" = {
      name = "image-size";
      packageName = "image-size";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-size/-/image-size-0.5.5.tgz";
        sha512 = "6TDAlDPZxUFCv+fuOkIoXT/V/f3Qbq8e37p+YOiYrUv3v9cc3/6x78VdfPgFVaB9dZYeLUfKgHRebpkm/oP2VQ==";
      };
    };
    "immutable-5.0.3" = {
      name = "immutable";
      packageName = "immutable";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-5.0.3.tgz";
        sha512 = "P8IdPQHq3lA1xVeBRi5VPqUm5HDgKnx0Ru51wZz5mjxHr5n3RWhjIpOFU7ybkUxfB+5IToy+OLaHYDBIWsv+uw==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-what-3.14.1" = {
      name = "is-what";
      packageName = "is-what";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-what/-/is-what-3.14.1.tgz";
        sha512 = "sNxgpk9793nzSs7bA6JQJGeIuRBQhAaNGG77kzYQgMkrID+lS6SlK07K5LaptscDlSaIgH+GPFzf+d75FVxozA==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "jackspeak-3.4.3" = {
      name = "jackspeak";
      packageName = "jackspeak";
      version = "3.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/jackspeak/-/jackspeak-3.4.3.tgz";
        sha512 = "OGlZQpz2yfahA/Rd1Y8Cd9SIEsqvXkLVoSw/cgwhnhFMDbsQFeZYoJJ7bIZBS9BcamUW96asq/npPWugM+RQBw==";
      };
    };
    "jiti-2.4.2" = {
      name = "jiti";
      packageName = "jiti";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-2.4.2.tgz";
        sha512 = "rg9zJN+G4n2nfJl5MW3BMygZX56zKPNVEYYqq7adpmMh4Jn2QNEwhvQlFy6jPVdcod7txZtKHWnyZiA3a0zP7A==";
      };
    };
    "laravel-vite-plugin-1.2.0" = {
      name = "laravel-vite-plugin";
      packageName = "laravel-vite-plugin";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/laravel-vite-plugin/-/laravel-vite-plugin-1.2.0.tgz";
        sha512 = "R0pJ+IcTVeqEMoKz/B2Ij57QVq3sFTABiFmb06gAwFdivbOgsUtuhX6N2MGLEArajrS3U5JbberzwOe7uXHMHQ==";
      };
    };
    "less-4.2.2" = {
      name = "less";
      packageName = "less";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/less/-/less-4.2.2.tgz";
        sha512 = "tkuLHQlvWUTeQ3doAqnHbNn8T6WX1KA8yvbKG9x4VtKtIjHsVKQZCH11zRgAfbDAXC2UNIg/K9BYAAcEzUIrNg==";
      };
    };
    "lightningcss-1.29.2" = {
      name = "lightningcss";
      packageName = "lightningcss";
      version = "1.29.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss/-/lightningcss-1.29.2.tgz";
        sha512 = "6b6gd/RUXKaw5keVdSEtqFVdzWnU5jMxTUjA2bVcMNPLwSQ08Sv/UodBVtETLCn7k4S1Ibxwh7k68IwLZPgKaA==";
      };
    };
    "lightningcss-linux-x64-gnu-1.29.3" = {
      name = "lightningcss-linux-x64-gnu";
      packageName = "lightningcss-linux-x64-gnu";
      version = "1.29.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-linux-x64-gnu/-/lightningcss-linux-x64-gnu-1.29.3.tgz";
        sha512 = "ySZTNCpbfbK8rqpKJeJR2S0g/8UqqV3QnzcuWvpI60LWxnFN91nxpSSwCbzfOXkzKfar9j5eOuOplf+klKtINg==";
      };
    };
    "linkify-it-5.0.0" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-5.0.0.tgz";
        sha512 = "5aHCbzQRADcdP+ATqnDuhhJ/MRIqDkZX5pyjFHRRysS8vZ5AbqGEoFIb6pYHPZ+L/OC2Lc+xT8uHVVR5CAK/wQ==";
      };
    };
    "linkifyjs-4.2.0" = {
      name = "linkifyjs";
      packageName = "linkifyjs";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkifyjs/-/linkifyjs-4.2.0.tgz";
        sha512 = "pCj3PrQyATaoTYKHrgWRF3SJwsm61udVh+vuls/Rl6SptiDhgE7ziUIudAedRY9QEfynmM7/RmLEfPUyw1HPCw==";
      };
    };
    "lodash.castarray-4.4.0" = {
      name = "lodash.castarray";
      packageName = "lodash.castarray";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.castarray/-/lodash.castarray-4.4.0.tgz";
        sha512 = "aVx8ztPv7/2ULbArGJ2Y42bG1mEQ5mGjpdvrbJcJFU3TbYybe+QlLS4pst9zV52ymy2in1KpFPiZnAOATxD4+Q==";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha512 = "oSXzaWypCMHkPC3NvBEaPHf0KsA5mvPrOPgQWDsbg8n7orZ290M0BmC/jgRZ4vcJ6DTAhjrsSYgdsW/F+MFOBA==";
      };
    };
    "lodash.merge-4.6.2" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.2.tgz";
        sha512 = "0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
      };
    };
    "lru-cache-10.4.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "10.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.4.3.tgz";
        sha512 = "JNAzZcXrCt42VGLuYz0zfAzDfAvJWW6AfYlDBQyDV5DClI2m5sAmK+OIO7s59XfsRsWHp02jAJrRadPRGTt6SQ==";
      };
    };
    "make-dir-2.1.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-2.1.0.tgz";
        sha512 = "LS9X+dc8KLxXCb8dni79fLIIUA5VyZoyjSMCwTluaXA0o27cCK0bhXkpgw+sTXVpPy/lSO57ilRixqk0vDmtRA==";
      };
    };
    "markdown-it-14.1.0" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "14.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-14.1.0.tgz";
        sha512 = "a54IwgWPaeBCAAsv13YgmALOF1elABB08FxO9i+r4VFk5Vl4pKokRPeX8u5TCgSsPi6ec1otfLjdOpVcgbpshg==";
      };
    };
    "mdurl-2.0.0" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-2.0.0.tgz";
        sha512 = "Lf+9+2r+Tdp5wXDXC4PcIBjTDtq4UKjCPMQhKIuzpJNW0b96kVqSwW0bT7FhRSfmAiFYgP+SCRvdrDozfh0U5w==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "mini-svg-data-uri-1.4.4" = {
      name = "mini-svg-data-uri";
      packageName = "mini-svg-data-uri";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mini-svg-data-uri/-/mini-svg-data-uri-1.4.4.tgz";
        sha512 = "r9deDe9p5FJUPZAk3A59wGH7Ii9YrjjWw0jmw/liSbHl2CHiyXj6FcDXDu2K3TjVAXqiJdaw3xxwlZZr9E6nHg==";
      };
    };
    "minimatch-9.0.5" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "9.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-9.0.5.tgz";
        sha512 = "G6T0ZX48xgozx7587koeX9Ys2NYy6Gmv//P89sEte9V9whIapMNF4idKxnW2QtCcLiTWlb/wfCabAtAFWhhBow==";
      };
    };
    "minipass-7.1.2" = {
      name = "minipass";
      packageName = "minipass";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-7.1.2.tgz";
        sha512 = "qOOzS1cBTWYF4BH8fVePDBOO9iptMnGUEZwNc/cMWnTV2nVLZ7VoNWEPHkYczZA0pdoA7dl6e7FL659nX9S2aw==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "nanoid-3.3.11" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.11.tgz";
        sha512 = "N8SpfPUnUp1bK+PMYW8qSWdl9U+wwNWI4QKxOYDy9JAro3WMX7p2OeVRF9v+347pnakNevPmiHhNmZ2HbFA76w==";
      };
    };
    "needle-3.3.1" = {
      name = "needle";
      packageName = "needle";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/needle/-/needle-3.3.1.tgz";
        sha512 = "6k0YULvhpw+RoLNiQCRKOl09Rv1dPLr8hHnVjHqdolKwDrdNyk+Hmrthi4lIGPPz3r39dLx0hsF5s40sZ3Us4Q==";
      };
    };
    "orderedmap-2.1.1" = {
      name = "orderedmap";
      packageName = "orderedmap";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/orderedmap/-/orderedmap-2.1.1.tgz";
        sha512 = "TvAWxi0nDe1j/rtMcWcIj94+Ffe6n7zhow33h40SKxmsmozs6dz/e+EajymfoFcHd7sxNn8yHM8839uixMOV6g==";
      };
    };
    "package-json-from-dist-1.0.1" = {
      name = "package-json-from-dist";
      packageName = "package-json-from-dist";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json-from-dist/-/package-json-from-dist-1.0.1.tgz";
        sha512 = "UEZIS3/by4OC8vL3P2dTXRETpebLI2NiI5vIrjaD/5UtrkFX/tNbwjTSRAGC/+7CAo2pIcBaRgWmcBBHcsaCIw==";
      };
    };
    "parse-node-version-1.0.1" = {
      name = "parse-node-version";
      packageName = "parse-node-version";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-node-version/-/parse-node-version-1.0.1.tgz";
        sha512 = "3YHlOa/JgH6Mnpr05jP9eDG254US9ek25LyIxZlDItp2iJtwyaXQb57lBYLdT3MowkUFYEV2XXNAYIPlESvJlA==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "path-scurry-1.11.1" = {
      name = "path-scurry";
      packageName = "path-scurry";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-scurry/-/path-scurry-1.11.1.tgz";
        sha512 = "Xa4Nw17FS9ApQFJ9umLiJS4orGjm7ZzwUrwamcGQuHSzDyth9boKDaycYdDcZDuqYATXw4HFXgaqWTctW/v1HA==";
      };
    };
    "picocolors-1.1.1" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz";
        sha512 = "xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "pify-4.0.1" = {
      name = "pify";
      packageName = "pify";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-4.0.1.tgz";
        sha512 = "uB80kBFb/tfd68bVleG9T5GGsGPjJrLAUpR5PZIrhBnIaRTQRjqdJSsIKkOP6OAIFbj7GOrcudc5pNjZ+geV2g==";
      };
    };
    "postcss-8.5.3" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.5.3.tgz";
        sha512 = "dle9A3yYxlBSrt8Fu+IpjGT8SY8hN0mlaA6GY8t0P5PjIOZemULz/E2Bnm/2dcUOena75OTNkHI76uZBNUUq3A==";
      };
    };
    "postcss-selector-parser-6.0.10" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "6.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-6.0.10.tgz";
        sha512 = "IQ7TZdoaqbT+LCpShg46jnZVlhWD2w6iQYAcYXfHARZ7X1t/UGhhceQDs5X0cGqKvYlHNOuv7Oa1xmb0oQuA3w==";
      };
    };
    "prosemirror-changeset-2.2.1" = {
      name = "prosemirror-changeset";
      packageName = "prosemirror-changeset";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-changeset/-/prosemirror-changeset-2.2.1.tgz";
        sha512 = "J7msc6wbxB4ekDFj+n9gTW/jav/p53kdlivvuppHsrZXCaQdVgRghoZbSS3kwrRyAstRVQ4/+u5k7YfLgkkQvQ==";
      };
    };
    "prosemirror-collab-1.3.1" = {
      name = "prosemirror-collab";
      packageName = "prosemirror-collab";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-collab/-/prosemirror-collab-1.3.1.tgz";
        sha512 = "4SnynYR9TTYaQVXd/ieUvsVV4PDMBzrq2xPUWutHivDuOshZXqQ5rGbZM84HEaXKbLdItse7weMGOUdDVcLKEQ==";
      };
    };
    "prosemirror-commands-1.7.0" = {
      name = "prosemirror-commands";
      packageName = "prosemirror-commands";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-commands/-/prosemirror-commands-1.7.0.tgz";
        sha512 = "6toodS4R/Aah5pdsrIwnTYPEjW70SlO5a66oo5Kk+CIrgJz3ukOoS+FYDGqvQlAX5PxoGWDX1oD++tn5X3pyRA==";
      };
    };
    "prosemirror-dropcursor-1.8.1" = {
      name = "prosemirror-dropcursor";
      packageName = "prosemirror-dropcursor";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-dropcursor/-/prosemirror-dropcursor-1.8.1.tgz";
        sha512 = "M30WJdJZLyXHi3N8vxN6Zh5O8ZBbQCz0gURTfPmTIBNQ5pxrdU7A58QkNqfa98YEjSAL1HUyyU34f6Pm5xBSGw==";
      };
    };
    "prosemirror-gapcursor-1.3.2" = {
      name = "prosemirror-gapcursor";
      packageName = "prosemirror-gapcursor";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-gapcursor/-/prosemirror-gapcursor-1.3.2.tgz";
        sha512 = "wtjswVBd2vaQRrnYZaBCbyDqr232Ed4p2QPtRIUK5FuqHYKGWkEwl08oQM4Tw7DOR0FsasARV5uJFvMZWxdNxQ==";
      };
    };
    "prosemirror-history-1.4.1" = {
      name = "prosemirror-history";
      packageName = "prosemirror-history";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-history/-/prosemirror-history-1.4.1.tgz";
        sha512 = "2JZD8z2JviJrboD9cPuX/Sv/1ChFng+xh2tChQ2X4bB2HeK+rra/bmJ3xGntCcjhOqIzSDG6Id7e8RJ9QPXLEQ==";
      };
    };
    "prosemirror-inputrules-1.5.0" = {
      name = "prosemirror-inputrules";
      packageName = "prosemirror-inputrules";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-inputrules/-/prosemirror-inputrules-1.5.0.tgz";
        sha512 = "K0xJRCmt+uSw7xesnHmcn72yBGTbY45vm8gXI4LZXbx2Z0jwh5aF9xrGQgrVPu0WbyFVFF3E/o9VhJYz6SQWnA==";
      };
    };
    "prosemirror-keymap-1.2.2" = {
      name = "prosemirror-keymap";
      packageName = "prosemirror-keymap";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-keymap/-/prosemirror-keymap-1.2.2.tgz";
        sha512 = "EAlXoksqC6Vbocqc0GtzCruZEzYgrn+iiGnNjsJsH4mrnIGex4qbLdWWNza3AW5W36ZRrlBID0eM6bdKH4OStQ==";
      };
    };
    "prosemirror-markdown-1.13.2" = {
      name = "prosemirror-markdown";
      packageName = "prosemirror-markdown";
      version = "1.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-markdown/-/prosemirror-markdown-1.13.2.tgz";
        sha512 = "FPD9rHPdA9fqzNmIIDhhnYQ6WgNoSWX9StUZ8LEKapaXU9i6XgykaHKhp6XMyXlOWetmaFgGDS/nu/w9/vUc5g==";
      };
    };
    "prosemirror-menu-1.2.4" = {
      name = "prosemirror-menu";
      packageName = "prosemirror-menu";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-menu/-/prosemirror-menu-1.2.4.tgz";
        sha512 = "S/bXlc0ODQup6aiBbWVsX/eM+xJgCTAfMq/nLqaO5ID/am4wS0tTCIkzwytmao7ypEtjj39i7YbJjAgO20mIqA==";
      };
    };
    "prosemirror-model-1.25.0" = {
      name = "prosemirror-model";
      packageName = "prosemirror-model";
      version = "1.25.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-model/-/prosemirror-model-1.25.0.tgz";
        sha512 = "/8XUmxWf0pkj2BmtqZHYJipTBMHIdVjuvFzMvEoxrtyGNmfvdhBiRwYt/eFwy2wA9DtBW3RLqvZnjurEkHaFCw==";
      };
    };
    "prosemirror-schema-basic-1.2.4" = {
      name = "prosemirror-schema-basic";
      packageName = "prosemirror-schema-basic";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-schema-basic/-/prosemirror-schema-basic-1.2.4.tgz";
        sha512 = "ELxP4TlX3yr2v5rM7Sb70SqStq5NvI15c0j9j/gjsrO5vaw+fnnpovCLEGIcpeGfifkuqJwl4fon6b+KdrODYQ==";
      };
    };
    "prosemirror-schema-list-1.5.1" = {
      name = "prosemirror-schema-list";
      packageName = "prosemirror-schema-list";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-schema-list/-/prosemirror-schema-list-1.5.1.tgz";
        sha512 = "927lFx/uwyQaGwJxLWCZRkjXG0p48KpMj6ueoYiu4JX05GGuGcgzAy62dfiV8eFZftgyBUvLx76RsMe20fJl+Q==";
      };
    };
    "prosemirror-state-1.4.3" = {
      name = "prosemirror-state";
      packageName = "prosemirror-state";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-state/-/prosemirror-state-1.4.3.tgz";
        sha512 = "goFKORVbvPuAQaXhpbemJFRKJ2aixr+AZMGiquiqKxaucC6hlpHNZHWgz5R7dS4roHiwq9vDctE//CZ++o0W1Q==";
      };
    };
    "prosemirror-tables-1.6.4" = {
      name = "prosemirror-tables";
      packageName = "prosemirror-tables";
      version = "1.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-tables/-/prosemirror-tables-1.6.4.tgz";
        sha512 = "TkDY3Gw52gRFRfRn2f4wJv5WOgAOXLJA2CQJYIJ5+kdFbfj3acR4JUW6LX2e1hiEBiUwvEhzH5a3cZ5YSztpIA==";
      };
    };
    "prosemirror-trailing-node-3.0.0" = {
      name = "prosemirror-trailing-node";
      packageName = "prosemirror-trailing-node";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-trailing-node/-/prosemirror-trailing-node-3.0.0.tgz";
        sha512 = "xiun5/3q0w5eRnGYfNlW1uU9W6x5MoFKWwq/0TIRgt09lv7Hcser2QYV8t4muXbEr+Fwo0geYn79Xs4GKywrRQ==";
      };
    };
    "prosemirror-transform-1.10.3" = {
      name = "prosemirror-transform";
      packageName = "prosemirror-transform";
      version = "1.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-transform/-/prosemirror-transform-1.10.3.tgz";
        sha512 = "Nhh/+1kZGRINbEHmVu39oynhcap4hWTs/BlU7NnxWj3+l0qi8I1mu67v6mMdEe/ltD8hHvU4FV6PHiCw2VSpMw==";
      };
    };
    "prosemirror-view-1.38.1" = {
      name = "prosemirror-view";
      packageName = "prosemirror-view";
      version = "1.38.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prosemirror-view/-/prosemirror-view-1.38.1.tgz";
        sha512 = "4FH/uM1A4PNyrxXbD+RAbAsf0d/mM0D/wAKSVVWK7o0A9Q/oOXJBrw786mBf2Vnrs/Edly6dH6Z2gsb7zWwaUw==";
      };
    };
    "prr-1.0.1" = {
      name = "prr";
      packageName = "prr";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-1.0.1.tgz";
        sha512 = "yPw4Sng1gWghHQWj0B3ZggWUm4qVbPwPFcRG8KyxiU7J2OHFSoEHKS+EZ3fv5l1t9CyCiop6l/ZYeWbrgoQejw==";
      };
    };
    "punycode.js-2.3.1" = {
      name = "punycode.js";
      packageName = "punycode.js";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode.js/-/punycode.js-2.3.1.tgz";
        sha512 = "uxFIHU0YlHYhDQtV4R9J6a52SLx28BCjT+4ieh7IGbgwVJWO+km431c4yRlREUAsAmt/uMjQUyQHNEPf0M39CA==";
      };
    };
    "readdirp-4.1.2" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-4.1.2.tgz";
        sha512 = "GDhwkLfywWL2s6vEjyhri+eXmfH6j1L7JE27WhqLeYzoh/A3DBaYGEj2H/HFZCn/kMfim73FXxEJTw06WtxQwg==";
      };
    };
    "rollup-4.36.0" = {
      name = "rollup";
      packageName = "rollup";
      version = "4.36.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-4.36.0.tgz";
        sha512 = "zwATAXNQxUcd40zgtQG0ZafcRK4g004WtEl7kbuhTWPvf07PsfohXl39jVUvPF7jvNAIkKPQ2XrsDlWuxBd++Q==";
      };
    };
    "rope-sequence-1.3.4" = {
      name = "rope-sequence";
      packageName = "rope-sequence";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/rope-sequence/-/rope-sequence-1.3.4.tgz";
        sha512 = "UT5EDe2cu2E/6O4igUr5PSFs23nvvukicWHx6GnOPlHAiiYbzNuCRQCuiUdHJQcqKalLKlrYJnjY0ySGsXNQXQ==";
      };
    };
    "rxjs-7.8.2" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "7.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-7.8.2.tgz";
        sha512 = "dhKf903U/PQZY6boNNtAGdWbG85WAbjT/1xYoZIC7FAY0yWapOBQVsVrDl58W86//e1VpMNBtRV4MaXfdMySFA==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sass-1.86.0" = {
      name = "sass";
      packageName = "sass";
      version = "1.86.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass/-/sass-1.86.0.tgz";
        sha512 = "zV8vGUld/+mP4KbMLJMX7TyGCuUp7hnkOScgCMsWuHtns8CWBoz+vmEhoGMXsaJrbUP8gj+F1dLvVe79sK8UdA==";
      };
    };
    "sass-embedded-1.86.0" = {
      name = "sass-embedded";
      packageName = "sass-embedded";
      version = "1.86.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass-embedded/-/sass-embedded-1.86.0.tgz";
        sha512 = "Ibq5DzxjSf9f/IJmKeHVeXlVqiZWdRJF+RXy6v6UupvMYVMU5Ei+teSFBvvpPD5bB2QhhnU/OJlSM0EBCtfr9g==";
      };
    };
    "sax-1.4.1" = {
      name = "sax";
      packageName = "sax";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.4.1.tgz";
        sha512 = "+aWOz7yVScEGoKNd4PA10LZ8sk0A/z5+nXQG5giUO5rprX9jgYsTdov9qCchZiPIZezbZH+jRut8nPodFAX4Jg==";
      };
    };
    "semver-5.7.2" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.2.tgz";
        sha512 = "cBznnQ9KjJqU67B52RMC65CMarK2600WFnbkcaiwWq3xy/5haFJlshgnpjovMVJ+Hff49d8GEn0b87C5pDQ10g==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-4.1.0" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
        sha512 = "bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
      };
    };
    "sortablejs-1.15.6" = {
      name = "sortablejs";
      packageName = "sortablejs";
      version = "1.15.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/sortablejs/-/sortablejs-1.15.6.tgz";
        sha512 = "aNfiuwMEpfBM/CN6LY0ibyhxPfPbyFeBTYJKCvzkJ2GkUpazIt3H+QIPAMHwqQ7tMKaHz1Qj+rJJCqljnf4p3A==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-0.7.4" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.7.4.tgz";
        sha512 = "l3BikUxvPOcn5E74dZiq5BGsTb5yEwhaTSzccU6t4sDOH8NWJCstKO5QT2CvtFoK6F0saL7p9xHAqHOlCPJygA==";
      };
    };
    "source-map-js-1.2.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz";
        sha512 = "UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
      };
    };
    "source-map-support-0.5.21" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz";
        sha512 = "uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string-width-5.1.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-5.1.2.tgz";
        sha512 = "HnLOCR3vjcY8beoNLtcjZ5/nxn2afmME6lhrDrebokqMap+XbeW8n9TXpPDOqdGK5qcI3oT0GKTW6wC7EMiVqA==";
      };
    };
    "string-width-cjs-4.2.3" = {
      name = "string-width-cjs";
      packageName = "string-width-cjs";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-ansi-7.1.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.0.tgz";
        sha512 = "iq6eVVI64nQQTRYq2KtEg2d2uU7LElhTJwsH4YzIHZshxlgZms/wIc4VoDQTlG/IvVIrBKG06CrZnp0qv7hkcQ==";
      };
    };
    "strip-ansi-cjs-6.0.1" = {
      name = "strip-ansi-cjs";
      packageName = "strip-ansi-cjs";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "stylus-0.64.0" = {
      name = "stylus";
      packageName = "stylus";
      version = "0.64.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylus/-/stylus-0.64.0.tgz";
        sha512 = "ZIdT8eUv8tegmqy1tTIdJv9We2DumkNZFdCF5mz/Kpq3OcTaxSuCAYZge6HKK2CmNC02G1eJig2RV7XTw5hQrA==";
      };
    };
    "sugarss-5.0.0" = {
      name = "sugarss";
      packageName = "sugarss";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sugarss/-/sugarss-5.0.0.tgz";
        sha512 = "3//knMoF9btXcxHTbMRckIYjkEzSZ6pZjiaZ3wM6OIpUtQ06Uwqc0XgAr6jf+U74cLLTV/BEgmHWoeXPC+NhdQ==";
      };
    };
    "supports-color-8.1.1" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-8.1.1.tgz";
        sha512 = "MpUEN2OodtUzxvKQl72cUF7RQ5EiHsGvSsVG0ia9c5RbWGL2CI4C7EpPS8UTBIplnlzZiNuV56w+FuNxy3ty2Q==";
      };
    };
    "sync-child-process-1.0.2" = {
      name = "sync-child-process";
      packageName = "sync-child-process";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sync-child-process/-/sync-child-process-1.0.2.tgz";
        sha512 = "8lD+t2KrrScJ/7KXCSyfhT3/hRq78rC0wBFqNJXv3mZyn6hW2ypM05JmlSvtqRbeq6jqA94oHbxAr2vYsJ8vDA==";
      };
    };
    "sync-message-port-1.1.3" = {
      name = "sync-message-port";
      packageName = "sync-message-port";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sync-message-port/-/sync-message-port-1.1.3.tgz";
        sha512 = "GTt8rSKje5FilG+wEdfCkOcLL7LWqpMlr2c3LRuKt/YXxcJ52aGSbGBAdI4L3aaqfrBt6y711El53ItyH1NWzg==";
      };
    };
    "tailwindcss-4.0.15" = {
      name = "tailwindcss";
      packageName = "tailwindcss";
      version = "4.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/tailwindcss/-/tailwindcss-4.0.15.tgz";
        sha512 = "6ZMg+hHdMJpjpeCCFasX7K+U615U9D+7k5/cDK/iRwl6GptF24+I/AbKgOnXhVKePzrEyIXutLv36n4cRsq3Sg==";
      };
    };
    "tapable-2.2.1" = {
      name = "tapable";
      packageName = "tapable";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tapable/-/tapable-2.2.1.tgz";
        sha512 = "GNzQvQTOIP6RyTfE2Qxb8ZVlNmw0n88vp1szwWRimP02mnTsx3Wtn5qRdqY9w2XduFNUgvOwhNnQsjwCp+kqaQ==";
      };
    };
    "terser-5.39.0" = {
      name = "terser";
      packageName = "terser";
      version = "5.39.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser/-/terser-5.39.0.tgz";
        sha512 = "LBAhFyLho16harJoWMg/nZsQYgTrg5jXOn2nCYjRUcZZEdE3qa2zb8QEDRUGVZBW4rlazf2fxkg8tztybTaqWw==";
      };
    };
    "tslib-2.8.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz";
        sha512 = "oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==";
      };
    };
    "uc.micro-2.1.0" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-2.1.0.tgz";
        sha512 = "ARDJmphmdvUk6Glw7y9DQ2bFkKBHwQHLi2lsaH6PPmz/Ka9sFOBsBluozhDltWmnv9u/cF6Rt87znRTPV+yp/A==";
      };
    };
    "undici-types-6.20.0" = {
      name = "undici-types";
      packageName = "undici-types";
      version = "6.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici-types/-/undici-types-6.20.0.tgz";
        sha512 = "Ny6QZ2Nju20vw1SRHe3d9jVu6gJ+4e3+MMpqu7pqE5HT6WsTSlce++GQmK5UXS8mzV8DSYHrQH+Xrf2jVcuKNg==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "varint-6.0.0" = {
      name = "varint";
      packageName = "varint";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/varint/-/varint-6.0.0.tgz";
        sha512 = "cXEIW6cfr15lFv563k4GuVuW/fiwjknytD37jIOLSdSWuOI6WnO/oKwmP2FQTU2l01LP8/M5TSAJpzUaGe3uWg==";
      };
    };
    "vite-5.4.14" = {
      name = "vite";
      packageName = "vite";
      version = "5.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/vite/-/vite-5.4.14.tgz";
        sha512 = "EK5cY7Q1D8JNhSaPKVK4pwBFvaTmZxEnoKXLG/U9gmdDcihQGNzFlgIvaxezFR4glP1LsuiedwMBqCXH3wZccA==";
      };
    };
    "vite-plugin-full-reload-1.2.0" = {
      name = "vite-plugin-full-reload";
      packageName = "vite-plugin-full-reload";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vite-plugin-full-reload/-/vite-plugin-full-reload-1.2.0.tgz";
        sha512 = "kz18NW79x0IHbxRSHm0jttP4zoO9P9gXh+n6UTwlNKnviTTEpOlum6oS9SmecrTtSr+muHEn5TUuC75UovQzcA==";
      };
    };
    "w3c-keyname-2.2.8" = {
      name = "w3c-keyname";
      packageName = "w3c-keyname";
      version = "2.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/w3c-keyname/-/w3c-keyname-2.2.8.tgz";
        sha512 = "dpojBhNsCNN7T82Tm7k26A6G9ML3NkhDsnw9n/eoxSRlVBB4CEtIQ/KTCLI2Fwf3ataSXRhYFkQi3SlnFwPvPQ==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wrap-ansi-8.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-8.1.0.tgz";
        sha512 = "si7QWI6zUMq56bESFvagtmzMdGOtoxfR+Sez11Mobfc7tm+VkUckk9bW2UeffTGVUbOksxmSw0AA2gs8g71NCQ==";
      };
    };
    "wrap-ansi-cjs-7.0.0" = {
      name = "wrap-ansi-cjs";
      packageName = "wrap-ansi-cjs";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "zeed-dom-0.15.1" = {
      name = "zeed-dom";
      packageName = "zeed-dom";
      version = "0.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/zeed-dom/-/zeed-dom-0.15.1.tgz";
        sha512 = "dtZ0aQSFyZmoJS0m06/xBN1SazUBPL5HpzlAcs/KcRW0rzadYw12deQBjeMhGKMMeGEp7bA9vmikMLaO4exBcg==";
      };
    };
  };
  args = {
    name = "twasgood";
    packageName = "twasgood";
    src = ./.;
    dependencies = [
      sources."@adobe/css-tools-4.3.3"
      sources."@bufbuild/protobuf-2.2.5"
      sources."@esbuild/linux-x64-0.21.5"
      sources."@isaacs/cliui-8.0.2"
      sources."@jridgewell/gen-mapping-0.3.8"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/set-array-1.2.1"
      sources."@jridgewell/source-map-0.3.6"
      sources."@jridgewell/sourcemap-codec-1.5.0"
      sources."@jridgewell/trace-mapping-0.3.25"
      sources."@remirror/core-constants-3.0.0"
      sources."@rollup/rollup-linux-x64-gnu-4.36.0"
      sources."@tailwindcss/forms-0.5.10"
      sources."@tailwindcss/node-4.0.15"
      sources."@tailwindcss/oxide-4.0.15"
      sources."@tailwindcss/oxide-linux-x64-gnu-4.0.15"
      sources."@tailwindcss/typography-0.5.16"
      sources."@tailwindcss/vite-4.0.15"
      sources."@tiptap/core-2.11.5"
      sources."@tiptap/extension-blockquote-2.11.5"
      sources."@tiptap/extension-bold-2.11.5"
      sources."@tiptap/extension-bullet-list-2.11.5"
      sources."@tiptap/extension-code-2.11.5"
      sources."@tiptap/extension-code-block-2.11.5"
      sources."@tiptap/extension-document-2.11.5"
      sources."@tiptap/extension-dropcursor-2.11.5"
      sources."@tiptap/extension-gapcursor-2.11.5"
      sources."@tiptap/extension-hard-break-2.11.5"
      sources."@tiptap/extension-heading-2.11.5"
      sources."@tiptap/extension-history-2.11.5"
      sources."@tiptap/extension-horizontal-rule-2.11.5"
      sources."@tiptap/extension-italic-2.11.5"
      sources."@tiptap/extension-link-2.11.5"
      sources."@tiptap/extension-list-item-2.11.5"
      sources."@tiptap/extension-ordered-list-2.11.5"
      sources."@tiptap/extension-paragraph-2.11.5"
      sources."@tiptap/extension-strike-2.11.5"
      sources."@tiptap/extension-text-2.11.5"
      sources."@tiptap/extension-text-style-2.11.5"
      sources."@tiptap/html-2.11.5"
      sources."@tiptap/pm-2.11.5"
      sources."@tiptap/starter-kit-2.11.5"
      sources."@types/estree-1.0.6"
      sources."@types/linkify-it-5.0.0"
      sources."@types/markdown-it-14.1.2"
      sources."@types/mdurl-2.0.0"
      sources."@types/node-22.13.11"
      sources."acorn-8.14.1"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-6.2.1"
      sources."argparse-2.0.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-2.0.1"
      sources."buffer-builder-0.2.0"
      sources."buffer-from-1.1.2"
      sources."chokidar-4.0.3"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."colorjs.io-0.5.2"
      sources."commander-2.20.3"
      sources."copy-anything-2.0.6"
      sources."crelt-1.0.6"
      sources."cross-spawn-7.0.6"
      sources."css-what-6.1.0"
      sources."cssesc-3.0.0"
      sources."debug-4.4.0"
      sources."detect-libc-2.0.3"
      sources."eastasianwidth-0.2.0"
      sources."emoji-regex-9.2.2"
      sources."enhanced-resolve-5.18.1"
      sources."entities-5.0.0"
      sources."errno-0.1.8"
      sources."esbuild-0.21.5"
      sources."escape-string-regexp-4.0.0"
      sources."foreground-child-3.3.1"
      sources."glob-10.4.5"
      sources."graceful-fs-4.2.11"
      sources."has-flag-4.0.0"
      sources."iconv-lite-0.6.3"
      sources."image-size-0.5.5"
      sources."immutable-5.0.3"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-what-3.14.1"
      sources."isexe-2.0.0"
      sources."jackspeak-3.4.3"
      sources."jiti-2.4.2"
      sources."laravel-vite-plugin-1.2.0"
      sources."less-4.2.2"
      sources."lightningcss-1.29.2"
      sources."lightningcss-linux-x64-gnu-1.29.3"
      sources."linkify-it-5.0.0"
      sources."linkifyjs-4.2.0"
      sources."lodash.castarray-4.4.0"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.merge-4.6.2"
      sources."lru-cache-10.4.3"
      sources."make-dir-2.1.0"
      (sources."markdown-it-14.1.0" // {
        dependencies = [
          sources."entities-4.5.0"
        ];
      })
      sources."mdurl-2.0.0"
      sources."mime-1.6.0"
      sources."mini-svg-data-uri-1.4.4"
      sources."minimatch-9.0.5"
      sources."minipass-7.1.2"
      sources."ms-2.1.3"
      sources."nanoid-3.3.11"
      sources."needle-3.3.1"
      sources."orderedmap-2.1.1"
      sources."package-json-from-dist-1.0.1"
      sources."parse-node-version-1.0.1"
      sources."path-key-3.1.1"
      sources."path-scurry-1.11.1"
      sources."picocolors-1.1.1"
      sources."picomatch-2.3.1"
      sources."pify-4.0.1"
      sources."postcss-8.5.3"
      sources."postcss-selector-parser-6.0.10"
      sources."prosemirror-changeset-2.2.1"
      sources."prosemirror-collab-1.3.1"
      sources."prosemirror-commands-1.7.0"
      sources."prosemirror-dropcursor-1.8.1"
      sources."prosemirror-gapcursor-1.3.2"
      sources."prosemirror-history-1.4.1"
      sources."prosemirror-inputrules-1.5.0"
      sources."prosemirror-keymap-1.2.2"
      sources."prosemirror-markdown-1.13.2"
      sources."prosemirror-menu-1.2.4"
      sources."prosemirror-model-1.25.0"
      sources."prosemirror-schema-basic-1.2.4"
      sources."prosemirror-schema-list-1.5.1"
      sources."prosemirror-state-1.4.3"
      sources."prosemirror-tables-1.6.4"
      sources."prosemirror-trailing-node-3.0.0"
      sources."prosemirror-transform-1.10.3"
      sources."prosemirror-view-1.38.1"
      sources."prr-1.0.1"
      sources."punycode.js-2.3.1"
      sources."readdirp-4.1.2"
      sources."rollup-4.36.0"
      sources."rope-sequence-1.3.4"
      sources."rxjs-7.8.2"
      sources."safer-buffer-2.1.2"
      sources."sass-1.86.0"
      sources."sass-embedded-1.86.0"
      sources."sax-1.4.1"
      sources."semver-5.7.2"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-4.1.0"
      sources."sortablejs-1.15.6"
      sources."source-map-0.6.1"
      sources."source-map-js-1.2.1"
      sources."source-map-support-0.5.21"
      sources."string-width-5.1.2"
      (sources."string-width-cjs-4.2.3" // {
        dependencies = [
          sources."emoji-regex-8.0.0"
          sources."strip-ansi-6.0.1"
        ];
      })
      (sources."strip-ansi-7.1.0" // {
        dependencies = [
          sources."ansi-regex-6.1.0"
        ];
      })
      sources."strip-ansi-cjs-6.0.1"
      (sources."stylus-0.64.0" // {
        dependencies = [
          sources."source-map-0.7.4"
        ];
      })
      sources."sugarss-5.0.0"
      sources."supports-color-8.1.1"
      sources."sync-child-process-1.0.2"
      sources."sync-message-port-1.1.3"
      sources."tailwindcss-4.0.15"
      sources."tapable-2.2.1"
      sources."terser-5.39.0"
      sources."tslib-2.8.1"
      sources."uc.micro-2.1.0"
      sources."undici-types-6.20.0"
      sources."util-deprecate-1.0.2"
      sources."varint-6.0.0"
      sources."vite-5.4.14"
      sources."vite-plugin-full-reload-1.2.0"
      sources."w3c-keyname-2.2.8"
      sources."which-2.0.2"
      sources."wrap-ansi-8.1.0"
      (sources."wrap-ansi-cjs-7.0.0" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."emoji-regex-8.0.0"
          sources."string-width-4.2.3"
          sources."strip-ansi-6.0.1"
        ];
      })
      sources."zeed-dom-0.15.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
