# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "@esbuild/linux-x64" = nodeEnv.buildNodePackage {
    name = "_at_esbuild_slash_linux-x64";
    packageName = "@esbuild/linux-x64";
    version = "0.24.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-0.24.2.tgz";
      sha512 = "8Qi4nQcCTbLnK9WoMjdC9NiTG6/E38RNICU6sUNqK0QFxCYgoARqVqxdFmWkdonVsvGqWhmm7MO0jyTqLqwj0Q==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The Linux 64-bit binary for esbuild, a JavaScript bundler.";
      homepage = "https://github.com/evanw/esbuild#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@rollup/rollup-linux-x64-gnu" = nodeEnv.buildNodePackage {
    name = "_at_rollup_slash_rollup-linux-x64-gnu";
    packageName = "@rollup/rollup-linux-x64-gnu";
    version = "4.32.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/@rollup/rollup-linux-x64-gnu/-/rollup-linux-x64-gnu-4.32.1.tgz";
      sha512 = "WQFLZ9c42ECqEjwg/GHHsouij3pzLXkFdz0UxHa/0OM12LzvX7DzedlY0SIEly2v18YZLRhCRoHZDxbBSWoGYg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Native bindings for Rollup";
      homepage = "https://rollupjs.org/";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@tailwindcss/oxide-linux-x64-gnu" = nodeEnv.buildNodePackage {
    name = "_at_tailwindcss_slash_oxide-linux-x64-gnu";
    packageName = "@tailwindcss/oxide-linux-x64-gnu";
    version = "4.0.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@tailwindcss/oxide-linux-x64-gnu/-/oxide-linux-x64-gnu-4.0.2.tgz";
      sha512 = "pBeqHB0dbwztF7PaKqW32b2v9lNdardjJjBISeqZMotdUrMtDf7MeIQ1w6/WIr2xMvZpMl76dz02KZlUVWiiXg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "This is the **x86_64-unknown-linux-gnu** binary for `@tailwindcss/oxide`";
      homepage = "https://github.com/tailwindlabs/tailwindcss#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  lightningcss-linux-x64-gnu = nodeEnv.buildNodePackage {
    name = "lightningcss-linux-x64-gnu";
    packageName = "lightningcss-linux-x64-gnu";
    version = "1.29.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/lightningcss-linux-x64-gnu/-/lightningcss-linux-x64-gnu-1.29.1.tgz";
      sha512 = "u1S+xdODy/eEtjADqirA774y3jLcm8RPtYztwReEXoZKdzgsHYPl0s5V52Tst+GKzqjebkULT86XMSxejzfISw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A CSS parser, transformer, and minifier written in Rust";
      homepage = "https://github.com/parcel-bundler/lightningcss#readme";
      license = "MPL-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
